### ISSUE TITLE
Lonely checkbox in tutorial

### ISSUE THREAD

**Issue by JorrieB** [MakeSchool-Tutorials/Peeved-Penguins-SpriteBuilder-Swift#2]
In the makeschool.com/sa tutorial for peeved penguins, there is a lone checkbox "did you complete this section?" at the very beginning. I don't see how that's happening in the markdown, so I haven't done anything to fix it.

**Comment by dionlarson** [comment]
Fixed in bbc934366ed4cba670cdf2f99609a91fa794177a
